name: .NET

on:
  push:
    branches: [ main, dev, feature/*, fix/*, release/* ]

  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          10.0.x
      # dotnet-quality: 'preview' # When using preview versions
        dotnet-quality: 'ga' # General Availability

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Restore solution
      run: dotnet restore ./../Dependency.slnx

    - name: Build solution
      run: dotnet build ./../Dependency.slnx --no-restore  -c Release

    - name: Test solution
      run: dotnet test ./../Dependency.slnx --no-restore  -c Release

    - name: Pack solution
      run: dotnet pack ./../Dependency.slnx --no-restore -o ~/nuget  -c Release

    - name: Push Packages
      if: ${{ github.event_name == 'release' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg"
        -s https://api.nuget.org/v3/index.json
        -k ${{ secrets.NuGetSourcePassword }}
        --skip-duplicate
